apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: prr
 namespace: green-prod
 labels:
  name: prr
spec:
  replicas: 1
  template:
    metadata:
      name: prr
      namespace: green-prod
      labels:
        tier: backend
        lang: nodejs
        name: prrservice
    spec:
      containers:
        - name: prr
          image: nexussrv.office.traffics-switch.de:9843/traffics/prrservice
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
          env:
            - name: NODE_ENV
              value: production
            - name: LOG_LEVEL
              value: info
            - name: DOCKER_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /alive
              port: web
            initialDelaySeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /alive
              port: web
            initialDelaySeconds: 3
            periodSeconds: 30
          volumeMounts:
            - name: trafficsinternalrootcacrt
              mountPath: "/etc/traffics/ssl/"
              readOnly: true
            - name: authserviceconfig
              mountPath: "/etc/authservice/config/"
              readOnly: true
          ports:
          - name: web
            containerPort: 3010
      volumes:
        - name: trafficsinternalrootcacrt
          secret:
            secretName: traffics-internal-root-ca-crt
        - name: authserviceconfig
          secret:
            secretName: auth-service-config
      imagePullSecrets:
        - name: nexusregisterykey
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prr
  namespace: green-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: prr
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
